# Generated by Django 6.0.3 on 2115-12-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('PG', 'Разыгрывающий'), ('SG', 'Атакующий защитник'), ('SF', 'Легкий форвард'), ('PF', 'Мощный форвард'), ('C', 'Центровой'), ('A', 'Игрок')], default='A', max_length=2, verbose_name='Позиция'),
        ),
    ]
