# Generated by Django 6.0.3 on 2115-12-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_email_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_roster',
            field=models.BooleanField(default=False, verbose_name='В основном составе'),
        ),
    ]
