# Generated by Django 6.0.3 on 2026-03-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_is_in_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фото игрока'),
        ),
    ]
