# Generated by Django 6.0.3 on 2026-03-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='jersey_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Игровой номер'),
        ),
    ]
